### ISSUE TITLE
add another tool gcloud

### ISSUE THREAD

**Issue by MuhammadJamee** [felipecrs/jenkins-agent-dind#69]
Hey @felipecrs I tried to add gcloud cli utility but didn't make it. will you help me to add that one?

**Comment by felipecrs** [comment]
Hi, the following should work:

```dockerfile
FROM ghcr.io/felipecrs/jenkins-agent-dind:latest

RUN \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list; \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | sudo tee /usr/share/keyrings/cloud.google.gpg; \
    sudo apt-get update; \
    sudo apt-get install google-cloud-cli -y
```

I'm in the process of actually removing the bloatware of the image (https://github.com/felipecrs/jenkins-agent-dind/issues/66), so I will not be adding `gcloud` to it by default.

**Comment by MuhammadJamee** [comment]
thanks

**Comment by felipecrs** [comment]
The image now comes with [pkgx](https://pkgx.sh/), meaning installing gcloud is now as simple as:

```console
$ pkgx install gcloud

$ gcloud --version
```
